[base]
image=fedora:43
hostname=fedora
# general
additional_packages="vim neovim gh htop iotop git zsh fzf timew python3-pip ripgrep fd-find arandr autorandr xclip atuin gawk feh calc cloc jq"
# tools
additional_packages="bind-utils"
# compiling
additional_packages="gcc-c++ make cmake openssl-devel mold luarocks python3-devel"
# for egui/eframe
additional_packages="clang clang-devel clang-tools-extra libxkbcommon-devel libxkbcommon-x11 pkg-config openssl-devel libxcb-devel gtk3-devel atk fontconfig-devel"
# work related
additional_packages="xfreerdp sshpass skopeo"
start_now=true
exported_bins="/usr/bin/htop /usr/bin/iotop /usr/bin/vim /bin/zsh /usr/bin/rg /usr/bin/timew /usr/sbin/autorandr /usr/sbin/feh"
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/docker;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/docker-compose;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/flatpak;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/podman;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/xdg-open;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/systemctl;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/rpm-ostree;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/bin/distrobox;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/sbin/lsof;
