set expandtab
set shiftwidth=2
set tabstop=4
set hidden
set relativenumber
set number
set undofile
set undodir=~/.local/share/vim/undo//
set title
set ignorecase
set smartcase
set wildmode=longest:full,full
set nowrap
" next two are for showing whitespace (leading tabs and trailing spaces)
set list
set listchars=tab:▸\ ,trail:·
" allow mouse usage in all modes
set mouse=a
set scrolloff=8
set sidescrolloff=8
" do not add two spaces when joining after . or ? or ! (shift+J in normal mode)
set nojoinspaces
set splitright
set clipboard=unnamedplus
set confirm
set exrc
set secure
set backup
set backupdir=~/.local/share/vim/backup//
set noswapfile
set updatetime=300 " Reduce time for highlighting other references
set redrawtime=10000 " Allow more time for loading syntax on large files
set grepprg=rg\ --vimgrep\ --smart-case\ --follow " use ripgrep instead of grep inside of vim
" automatically save after editing and read after file changed externally
set autowrite
set autoread

if has("autocmd")
" remember last edit position and restore it
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"
"  Keymaps
"

let mapleader = " "

nmap <leader>ve :edit ~/.vim/vimrc<cr>
nmap <leader>vr :w!<cr>:source ~/.vim/vimrc<cr>

" Allow gf to open non-existent files
map gf :edit <cfile><cr>

" Reselect visual selection after indenting
vnoremap < <gv
vnoremap > >gv  

imap jk <esc>

"--------------------------------------------------------------------------
" Plugins
"--------------------------------------------------------------------------

" Automatically install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin(data_dir . '/plugins')
source ~/.config/vim/plugins/all-vim-plugins.vim
call plug#end()

" this must happen after plugins are loaded, silent is added to avoid errors
" when autoinstalling plugins
silent! colorscheme everforest
