set expandtab
set shiftwidth=4
set tabstop=4
set hidden
set relativenumber
set number
set undofile
set title
set ignorecase
set smartcase
set wildmode=longest:full,full
set nowrap
set list
set listchars=tab:▸\ ,trail:·
set mouse=a
set scrolloff=8
set sidescrolloff=8
set nojoinspaces
set splitright
set clipboard=unnamedplus
set confirm
set exrc
set backup
set backupdir=~/.local/share/vim/backup//
set updatetime=300 " Reduce time for highlighting other references
set redrawtime=10000 " Allow more time for loading syntax on large files

"
"  Keymaps
"

let mapleader = " "
nmap <leader>ve :edit ~/.vim/vimrc<cr>
nmap <leader>vr :w!<cr>:source ~/.vim/vimrc<cr>

" Allow gf to open non-existent files
map gf :edit <cfile><cr>

" Reselect visual selection after indenting
vnoremap < <gv
vnoremap > >gv  

imap jk <esc>

"--------------------------------------------------------------------------
" Plugins
"--------------------------------------------------------------------------

" Automatically install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(data_dir . '/plugins')

" source ~/.config/vim/plugins/abolish.vim
source ~/.config/vim/plugins/everforest.vim
source ~/.config/vim/plugins/airline.vim
" source ~/.config/vim/plugins/arduino.vim
" source ~/.config/vim/plugins/coc.vim
source ~/.config/vim/plugins/commentary.vim
" source ~/.config/vim/plugins/context-commentstring.vim
" source ~/.config/vim/plugins/dispatch.vim
" source ~/.config/vim/plugins/dracula.vim
" source ~/.config/vim/plugins/editorconfig.vim
" source ~/.config/vim/plugins/eunuch.vim
" source ~/.config/vim/plugins/exchange.vim
" source ~/.config/vim/plugins/firevim.vim
" source ~/.config/vim/plugins/floaterm.vim
" source ~/.config/vim/plugins/fugitive.vim
" source ~/.config/vim/plugins/fzf.vim
" source ~/.config/vim/plugins/heritage.vim
" source ~/.config/vim/plugins/lastplace.vim
" source ~/.config/vim/plugins/lion.vim
" source ~/.config/vim/plugins/markdown-preview.vim
" source ~/.config/vim/plugins/nerdtree.vim
" source ~/.config/vim/plugins/pasta.vim
" source ~/.config/vim/plugins/peekaboo.vim
" source ~/.config/vim/plugins/phpactor.vim
" source ~/.config/vim/plugins/polyglot.vim
" source ~/.config/vim/plugins/projectionist.vim
" source ~/.config/vim/plugins/quickscope.vim
" source ~/.config/vim/plugins/repeat.vim
" source ~/.config/vim/plugins/rooter.vim
" source ~/.config/vim/plugins/sayonara.vim
" source ~/.config/vim/plugins/smooth-scroll.vim
" source ~/.config/vim/plugins/splitjoin.vim
" source ~/.config/vim/plugins/surround.vim
" source ~/.config/vim/plugins/targets.vim
" source ~/.config/vim/plugins/textobj-xmlattr.vim
" source ~/.config/vim/plugins/tmux-navigator.vim
" source ~/.config/vim/plugins/unimpaired.vim
" source ~/.config/vim/plugins/vim-test.vim
" source ~/.config/vim/plugins/visual-multi.vim
" source ~/.config/vim/plugins/visual-star-search.vim
" source ~/.config/vim/plugins/which-key.vim

call plug#end()

" this must happen after plugins are loaded, silent is added to avoid errors
" when autoinstalling plugins
silent! colorscheme everforest
